<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OrganizationMember;

class OrganizationMemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            // Dewan Pembina
            [
                'member_number' => 'MKT-PB-001',
                'name' => 'H. Ahmad Dahlan, S.E., M.M.',
                'tier' => 'Dewan Pembina',
                'position' => 'Ketua Dewan Pembina',
                'division' => 'Pembina & Pengarah Utama',
                'email' => 'ahmad.dahlan@mkt-charity.org',
                'phone' => '081234567801',
                'address' => 'Jl. Kebon Jeruk No. 12, Jakarta Barat',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 1,
                'notes' => 'Tokoh pendiri yayasan kemanusiaan MKT',
            ],
            [
                'member_number' => 'MKT-PB-002',
                'name' => 'Dr. Hj. Siti Nurjanah, M.Si.',
                'tier' => 'Dewan Pembina',
                'position' => 'Anggota Dewan Pembina',
                'division' => 'Pembina Kemitraan & Kebijakan',
                'email' => 'siti.nurjanah@mkt-charity.org',
                'phone' => '081234567802',
                'address' => 'Jl. Sudirman No. 45, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 2,
                'notes' => 'Pakar sosial dan pemberdayaan masyarakat',
            ],

            // Dewan Pengawas
            [
                'member_number' => 'MKT-PW-001',
                'name' => 'Ir. Budi Santoso, M.T.',
                'tier' => 'Dewan Pengawas',
                'position' => 'Ketua Dewan Pengawas',
                'division' => 'Pengawasan Audit & Operasional',
                'email' => 'budi.santoso@mkt-charity.org',
                'phone' => '081234567803',
                'address' => 'Jl. Gatot Subroto No. 88, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 1,
                'notes' => 'Pengawas kepatuhan & transparansi donasi',
            ],
            [
                'member_number' => 'MKT-PW-002',
                'name' => 'H. Hendra Wijaya, S.H., M.H.',
                'tier' => 'Dewan Pengawas',
                'position' => 'Anggota Dewan Pengawas',
                'division' => 'Pengawasan Hukum & Legality',
                'email' => 'hendra.wijaya@mkt-charity.org',
                'phone' => '081234567804',
                'address' => 'Jl. Rasuna Said No. 10, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 2,
                'notes' => 'Konsultan hukum independen yayasan',
            ],

            // Pengurus Harian / Eksekutif
            [
                'member_number' => 'MKT-PG-001',
                'name' => 'Muhammad Ridwan, S.Kom.',
                'tier' => 'Pengurus',
                'position' => 'Ketua Umum',
                'division' => 'Pengurus Eksekutif',
                'email' => 'ridwan@mkt-charity.org',
                'phone' => '081234567805',
                'address' => 'Jl. Mampang Prapatan No. 5, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 1,
                'notes' => 'Penanggung jawab eksekutif seluruh program MKT',
            ],
            [
                'member_number' => 'MKT-PG-002',
                'name' => 'Siti Rahmah, S.Pd.',
                'tier' => 'Pengurus',
                'position' => 'Sekretaris Umum',
                'division' => 'Kesekretariatan & Administrasi',
                'email' => 'siti.rahmah@mkt-charity.org',
                'phone' => '081234567806',
                'address' => 'Jl. Tebet Raya No. 34, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 2,
                'notes' => 'Pengelola arsip, korespondensi, dan notulensi rapat',
            ],
            [
                'member_number' => 'MKT-PG-003',
                'name' => 'Agus Prasetyo, S.E.',
                'tier' => 'Pengurus',
                'position' => 'Bendahara Umum',
                'division' => 'Keuangan & Akuntansi',
                'email' => 'agus.prasetyo@mkt-charity.org',
                'phone' => '081234567807',
                'address' => 'Jl. Kemang Raya No. 19, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 3,
                'notes' => 'Pengelola keuangan & penyusunan laporan neraca',
            ],
            [
                'member_number' => 'MKT-PG-004',
                'name' => 'Captain Rian Hidayat',
                'tier' => 'Pengurus',
                'position' => 'Kabid Rescue & Tanggap Bencana',
                'division' => 'Tim Operasional Rescue',
                'email' => 'rian.rescue@mkt-charity.org',
                'phone' => '081234567808',
                'address' => 'Jl. Pos Pengungsian No. 1, Bogor',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 4,
                'notes' => 'Komandan posko utama evakuasi bencana lapangan',
            ],
            [
                'member_number' => 'MKT-PG-005',
                'name' => 'Dr. Andi Kurniawan',
                'tier' => 'Pengurus',
                'position' => 'Kabid Medis & Donor Darah',
                'division' => 'Layanan Kesehatan & Donor',
                'email' => 'andi.kurniawan@mkt-charity.org',
                'phone' => '081234567809',
                'address' => 'Jl. Kesehatan No. 7, Jakarta Pusat',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 5,
                'notes' => 'Koor. dokter tim medis darurat & jaringan PMI',
            ],
            [
                'member_number' => 'MKT-PG-006',
                'name' => 'Eka Putri, S.I.Kom.',
                'tier' => 'Pengurus',
                'position' => 'Kabid Humas & Donatur',
                'division' => 'Humas & Public Relations',
                'email' => 'eka.putri@mkt-charity.org',
                'phone' => '081234567810',
                'address' => 'Jl. Bangka Raya No. 40, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2029',
                'order_index' => 6,
                'notes' => 'Penanggung jawab publikasi media & jaringan donatur',
            ],

            // Anggota Aktif
            [
                'member_number' => 'MKT-AG-001',
                'name' => 'Farhan Abdillah',
                'tier' => 'Anggota',
                'position' => 'Anggota Relawan Rescue',
                'division' => 'Tim Rescuer',
                'email' => 'farhan@mkt-charity.org',
                'phone' => '081234567811',
                'address' => 'Jl. Cilandak KKO No. 15, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2026',
                'order_index' => 1,
                'notes' => 'Relawan bersertifikat SAR & Water Rescue',
            ],
            [
                'member_number' => 'MKT-AG-002',
                'name' => 'Dewi Lestari',
                'tier' => 'Anggota',
                'position' => 'Anggota Tim Donor Darah',
                'division' => 'Donor Darah Rutin',
                'email' => 'dewi.lestari@mkt-charity.org',
                'phone' => '081234567812',
                'address' => 'Jl. Kebayoran Lama No. 22, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2026',
                'order_index' => 2,
                'notes' => 'Pendonor aktif golongan darah O+',
            ],
            [
                'member_number' => 'MKT-AG-003',
                'name' => 'Bambang Sukismo',
                'tier' => 'Anggota',
                'position' => 'Anggota Logistik & Gudang',
                'division' => 'Gudang & Distribusi',
                'email' => 'bambang@mkt-charity.org',
                'phone' => '081234567813',
                'address' => 'Jl. Pasar Minggu No. 50, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2026',
                'order_index' => 3,
                'notes' => 'Relawan pengangkut & penyortir bantuan bencana',
            ],
            [
                'member_number' => 'MKT-AG-004',
                'name' => 'Rina Kartika',
                'tier' => 'Anggota',
                'position' => 'Anggota Relawan Medis',
                'division' => 'Tim Dapur Umum & Medis',
                'email' => 'rina.k@mkt-charity.org',
                'phone' => '081234567814',
                'address' => 'Jl. Lenteng Agung No. 8, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2026',
                'order_index' => 4,
                'notes' => 'Perawat pendamping medis tanggap darurat',
            ],
            [
                'member_number' => 'MKT-AG-005',
                'name' => 'Yudi Hermawan',
                'tier' => 'Anggota',
                'position' => 'Anggota Driver Ambulans',
                'division' => 'Transportasi & Armada',
                'email' => 'yudi@mkt-charity.org',
                'phone' => '081234567815',
                'address' => 'Jl. Jagakarsa No. 3, Jakarta Selatan',
                'status' => 'Aktif',
                'period' => '2024 - 2026',
                'order_index' => 5,
                'notes' => 'Driver ambulans MKT siaga 24 jam',
            ],
        ];

        foreach ($members as $member) {
            OrganizationMember::updateOrCreate(
                ['member_number' => $member['member_number']],
                $member
            );
        }
    }
}
